services:

  nginx:
    build:
      context: ./nginx
      
    ports:
      - "8080:80"
    depends_on:
      - test-server
    restart: unless-stopped

  test-server:
    build:
      context: ../servers
    environment:
      - PORT=8080
    restart: unless-stopped
