upstream backend_pool {
    server smartload-test-backend-1:8080 weight=1 max_fails=0;
    server smartload-test-backend-2:8080 weight=1 max_fails=0;
    server smartload-test-backend-3:8080 weight=1 max_fails=0;
    server smartload-test-backend-4:8080 weight=1 max_fails=0;
    server smartload-test-backend-5:8080 weight=1 max_fails=0;
}
